name: model41                       # model's name
epochs: 200                         # number of max epochs for training
seed: 42
metrics:
  - accuracy
# Optimizer
optimizer:
  type: Adam
  params:
    lr: !float 1e-4                 # starting learning rate
# Loss function
loss:
  type: CategoricalCrossentropy
  params:
# Callbacks
callbacks:                          # add or remove callbacks
  - type: ReduceLROnPlateau         # callbacks 1
    params:
      monitor: val_loss
      patience: 5
      min_lr: !float 1e-7
      factor: 0.2
  - type: EarlyStopping             # callbacks 2
    params:
      monitor: val_loss
      patience: 10
      restore_best_weights: True
                                    # callbacks N ...
# Input
input_layer:                        # settings for the input layer
  type: Input
  params:
    shape: !tuple [256, 256, 3]
    name: Input
# Output
output_layer:                       # settings for the output layer
  type: Dense
  params:
    units: 14
    activation: softmax
    name: Output
# Hidden
hidden_layers:                      # list of hidden layers (and their settings)
  # supernet
  - type: VGG16
    trainable_layers: 14            # specify the index of the first layer where to start unlocking for training
    params:
      include_top: False
      weights: imagenet
      input_shape: !tuple [256, 256, 3]
  # conv blocks
  - type: Conv2D
    params:
      filters: 32
      kernel_size: !tuple [3, 3]
      strides: !tuple [ 1, 1]
      padding: same
      activation: relu
      name: conv1
  - type: MaxPooling2D
    params:
      pool_size: !tuple [ 2, 2]
      name: pool1
  - type: Conv2D
    params:
      filters: 64
      kernel_size: !tuple [ 3, 3]
      strides: !tuple [ 1, 1]
      padding: same
      activation: relu
      name: conv2
  - type: MaxPooling2D
    params:
      pool_size: !tuple [ 2, 2]
      name: pool2
  - type: Conv2D
    params:
      filters: 128
      kernel_size: !tuple [ 3, 3]
      strides: !tuple [ 1, 1]
      padding: same
      activation: relu
      name: conv3
  - type: MaxPooling2D
    params:
      pool_size: !tuple [ 2, 2]
      name: pool3
  # flattening
  - type: Flatten
    params:
      name: flatten
  - type: Dropout
    params:
      name: drop1
      rate: 0.3
      seed: 42
  # classification
  - type: Dense
    params:
      units: 256
      activation: relu
      name: class
  - type: Dropout
    params:
      rate: 0.3
      seed: 42
      name: drop2
